### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by brekk**
Hey @ezolenko,

I saw in the [README](https://github.com/ezolenko/rollup-plugin-typescript2#contributing) that you needed some unit tests -- I tried to add some decent coverage for the files here (though I think I may have misunderstood the build process (specifically the `tsProxy` stuff); if this branch is useful I'm happy to amend / continue this branch but as I'm about to start a new job in a couple days I figured it would be better to post this as is rather than let it languish.

screen shot 2019-02-02 at 1 58 16 pm

Additionally this is the first time I've written unit tests for TS -- I did some dirty checking of instances via `instance as any` but I think in general it has decent coverage for the files I started tests for.

I hope it's ok, feedback appreciated.

Thanks,

Brekk

### CODE REVIEW

**Comment by brekk** [comment]
Oh, also `yarn test` or `npm run test` or `jest --verbose --coverage` are the current ways I run tests.

**Comment by ezolenko** [comment]
Thanks! I'll check it out soon

**Comment by brekk** [comment]
@ezolenko Hey I was just curious if there was any traction on this.

**Comment by ezolenko** [comment]
Yes and no sorry, I have problems executing this on windows, but I haven't looked too closely on what exactly was wrong yet.

**Comment by brekk** [comment]
@ezolenko I tried running the tests on my windows machine at work and was able to uncover two failures in the test suite which I have recently addressed -- please let me know if it ends up working on your end.

**Comment by ezolenko** [comment]
Thanks for the updates.

Could you merge everything from master and run a `npm build && npm build-self && npm build-self` cycle? I'm getting strange things from rollup when it makes bundle due to the way the imports are changed I think. 

Also, could you move *.spec.ts files into their own directory at the same level as source, so there is `<root>/src/*.ts` and `<root>/unittests/*.spec.ts` or something and make sure unittest artifacts don't make it into `dest`. (I can do that part myself once things are working if you don't get around to it)

**Comment by agilgur5** [comment]
I'm hoping to pick this PR/branch up soon, update it, and fix any issues. This plugin could _really_ use some tests and this PR has been on my radar for a while.

Will of course credit OP and use their commits as-is where possible (pending merge issues) or otherwise make them co-author if I make a new PR that gets squashed in.

**Comment by agilgur5** [comment]
Have a [WIP branch](https://github.com/agilgur5/rollup-plugin-typescript2/tree/test-add-unit-tests) of this now, fully rebased with 3 years of commits, updated deps, updated config, moved to `__tests__` dir, etc.
Working on updating the tests, fixing any build issues, and then adding CI action now; PR coming soon!

**Comment by agilgur5** [comment]
Replaced by #321

**Pull request closed without merging**
