### PR TITLE
fix(github): improve formatting of issue template spoilers

### PR DESCRIPTION
**Pull request by agilgur5**
## Summary

Improve formatting of the issue template with code blocks and fixing some duplication

## Details

- I originally added the spoilers in #244 and while they work (and I would say improve readability a good bit), there's also some issues with them
  - I've used them a ton more now so know how to workaround most of the issues with them now

- fix: use HTML `code` tag inside of `summary` tag, can't use backticks
  - was mixing MD and HTML before, and this doesn't always work and didn't work on GitHub, they just had visible backticks before

- fix: don't duplicate the file name in the heading, just make the `summary` have a heading inside it instead
  - use an `h4` same as the `####` that it was before

- feat: add syntax highlighting by adding code blocks for each code snippet
  - `js` for `rollup.config.js`, `json5` for `tsconfig` (it has comments, trailing commas, etc (actually a custom parser, but json5 is close enough)), `json` for `package.json`, and `text` for verbose logs
  - also, a lot of people sometimes just paste the code with no code block and it formats terribly, so this should help defer that (as well as any potential issues that can crop up with unindented blocks)
    - the `envinfo` `text` code block that I added in #245 seems to be working well and used in most issues, so hopefully this will improve issues too
    
## References

I wrote #310 using this format as an example! Think it's a good bit cleaner

- As for examples of how it previously looked and why this is better, #309 shows an example with no syntax highlighting but use of code blocks, whereas #306 uses no code blocks at all and so isn't formatted well and GitHub/Markdown doesn't indent it either. Both are properly using spoilers as well.

### CODE REVIEW

**Comment by ezolenko** [comment]
Looks good, thanks

**Comment by agilgur5** [comment]
@ezolenko unrelated, but would you want to give me "Triage" access to this repo? I occasionally go through the issues myself and respond myself, and figure as an experienced maintainer I can triage/format/edit/label/organize/etc a bunch of things as well as close out issues that I think are stale or have been resolved. Ones that I'm not sure of I'd leave to you of course -- we can work out what the specifics of that would look like as well.
Not that I have a ton of time myself, but I figure two is better than one any day, and I'm an occasional contributor anyway already. And I know from my own experience and from this repo's issues too that _a lot_ of time is spent on issues. 

Can see [TSDX's labels](https://github.com/jaredpalmer/tsdx/labels) for an example of what's probably the most organized repo I've maintained.

**Comment by ezolenko** [comment]
@agilgur5 Sure! Invite sent. I have almost no time for this repo, just enough to check incoming PRs and such, so any help is welcome

**Comment by agilgur5** [comment]
Thanks @ezolenko !

You've probably seen some of my work already if you have notifications turned on, but here's a quick summary/heads-up for your information:
1. Added something like [~40 labels](https://github.com/ezolenko/rollup-plugin-typescript2/labels) based on my past experience plus some specific ones for this repo. May add more specific ones moving forward as I see more patterns.
    - Changed the naming of existing labels to fit the label categories I use (`kind`, `scope`, `problem`, `solution`, `topic`)
    - Made this [fork](https://github.com/agilgur5/github-label-manager) of `github-label-manager` to help with adding all the labels too.
    - Standardized some label colors that I haven't done in all my repos yet (always a WIP)
1. Labeled and re-formatted 100+ open and closed issues
    - You'll see the labels everywhere now
    - You'll see `edited by agilgur5` in dozens of comments in all sorts of places where I reformatted for syntax highlighting, spoiler tags (like those here), added back-links, etc
1. Closed out around ~30 issues that were duplicative, stale, already responded to, etc.
1. Responded to many more issues (~50?) either with closure notice, duplication notice, or with workarounds, possible resolutions, or confirmations of issues.

I've gone through most of the open issues now and about 2-3 pages of closed issues as well (will get to organizing the rest eventually)

<hr>

Some patterns I've noticed so far:
1. Many issues are ones where `tsc` would have similar behavior, so they are not bugs. See [`solution: tsc behavior` label](https://github.com/ezolenko/rollup-plugin-typescript2/issues?q=label%3A%22solution%3A+tsc+behavior%22)
1. Some are plugin order misconfigurations. See [`problem: plugin order` label](https://github.com/ezolenko/rollup-plugin-typescript2/issues?q=label%3A%22problem%3A+plugin+order%22+)
     - Planning to solve 1. and 2. with modifications to the issue template. I'll likely be iterating on that a bit, so stay tuned for PRs there as well as to a `CONTRIBUTING.md`
1. Many are missing reproductions or can't be easily reproduced.
    - Have actually been long planning (since I've been a contributor years ago) to add a simple Codesandbox or Stackblitz minimal environment for use in the issue template and for quick reproductions without installing a whole repo locally.
1. Some are incorrectly using this plugin's options. See #312 for my resolution for that     
1. Handful of cache issues resolved by `clean: true`. See [`scope: cache` label](https://github.com/ezolenko/rollup-plugin-typescript2/issues?q=label%3A%22scope%3A+cache%22+)
1. Some monorepo / symlink issues. See [`topic: monorepo / symlinks` label](https://github.com/ezolenko/rollup-plugin-typescript2/issues?q=label%3A%22topic%3A+monorepo+%2F+symlinks%22+)
    - Either some `realpath`ing is needed or these are more user-land issues that this plugin can't necessarily fix, i.e. things outside of the source directory or `tsconfig` `include` etc. Possibly a bit of both.
1. Type-only imports have been a long-standing, recurring source of issues.
    - I investigated more in https://github.com/ezolenko/rollup-plugin-typescript2/issues/298#issuecomment-1114249060 and would really like to solve this
1. A number of head-scratching issues where `tsc` acts different from this plugin. May be solved by some of the above.

**Comment by agilgur5** [comment]
## maintenance update

As of last week, I have officially gone through nearly 100% of all issues, open and closed, 250+ in total, as well as various PRs.

Other notable things:
  - Created the whole unit testing suite and got it to 100% coverage in the files it tests. CI now runs a matrix on multiple OSes and LTS Node versions to ensure compatibility. Integration testing is WIP
  - Refactored a decent bit of code for it to be simpler, use less deps, or be more readable
  - Have also been contributing to improving the release notes, `CONTRIBUTING.md`, etc.

1. Added a handful more [labels](https://github.com/ezolenko/rollup-plugin-typescript2/labels) specific to rpt2
1. Labeled and reformatted 100% of all open and closed issues.
    - A handful or so I haven't fully investigated or fixed, either because the complexity was high, or no repro was provided, etc. These can often be identified by their lack of labels (e.g. only one label) or lack of locking etc.
    - It was actually pretty insightful to look through old issues and get the history and context of this repo. In particular, some of the very early issues gave me a better understanding of certain historical design decisions and how certain features came to be.
1. Closed out another ~20 issues, down to 39 open ones now, many of which are either long-standing issues or have no repros / are stale
    - Many of these were actually fairly complex and so I gave detailed responses or even did root cause analysis for some.
    - The stale / no repro ones I'm hoping to make quick repros of once I create a repro environment (WIP) and then either close out or mark as bug and investigate.
1. Probably locked close to ~200 issues and PRs (maybe only 150? I didn't keep track, but it's the vast majority)

## patterns

1. This week we've released fixes to monorepos / symlinks, which are the 2nd most common issue in rpt2, after type-only imports.
1. Some of the `tsc` differences were indeed caused by this, but not sure if all of them
1. I've also RCA'd a good portion of the type-only imports issue and think I can get a fix out soon, although it's non-trivial and may need significant testing -- i.e. may want to add an integration test suite _first_ before releasing that fix (may work on those in parallel though). RCA will be written out in the respective issues.
1. repro environment is WIP (thinking of forking off https://repl.it/@rollup/rollup-plugin-repro that the `@rollup/plugins` monorepo uses, though I also played around with StackBlitz for one of my other OSS projects today -- repl.it has a significant portion of its codebase open-sourced (unlike StackBlitz), so I'm leaning in its direction)
1. issue template improvements are WIP (I've actually had an unfinished branch for that open for a while, was waiting to get the `CONTRIBUTING.md` and testing out first)
1. Integration issues with Vue and Svelte are somewhat common (c.f. #283, #129, etc)
1. Misconfigurations of `rootDir` causing TS to place types in a subdirectory (`dist/src`) is somewhat common (c.f. #275, #64)
1. Trying to use `tsconfig`'s `noEmitOnError` and not knowing about the plugin option `abortOnError` is fairly common (#254, #206, #62, #60, #31, etc). I'm hoping my recent PR #338 that added a note at the top of the docs helps abate this. Implementing #168 may also help obviate users' need to configure this option as well.
1. Downstream misconfiguration or version issues in libraries like `microbundle` are fairly common. See the new [`scope: downstream`](https://github.com/ezolenko/rollup-plugin-typescript2/issues?q=is%3Aissue+is%3Aclosed+label%3A%22scope%3A+downstream%22) label.
1. Confusion that I think is warranted around the plugin `include`/`exclude` vs the `tsconfig` `include`/`exclude` (#225, #280)


There are some one-off issues that aren't quite patterns but that I think are pretty important to fix, such as:
1. Multi-entry doesn't completely work out-of-the-box per #136
1. ^I think this may also impact code-splitting as well, esp. as I don't believe we'd produce typings for split chunks
1. Getting `files` to work per #211 .
This may be fixed by the type-only imports fix though, as it wouldn't rely on `parsedConfig.fileNames`/the `tsconfig` `include` anymore, and would instead use `ts.preProcessFile` to create an import chain.

Think that'll be the last update/maintenance summary I'll give since I've gone through all the issues now and these patterns are much smaller now. The few issues leftover don't really need a summary or are already part of previous patterns listed.

**Comment by ezolenko** [comment]
Awesome job, thanks a lot!

**Pull request merged**
